services:
  redis:
    image: redis:7.0
    restart: always
    container_name: redis
    ports:
      - "6379:6379"

  server:
    image: azk-notificator-server
    restart: always
    container_name: azk-notificator-server
    command: --queue-host redis
    ports:
      - "8080:80"

  sender:
    image: azk-notificator-sender
    container_name: azk-notificator-sender
    command: --server-host server
